### ISSUE TITLE
Manually building a tile server (20.04 LTS)

### ISSUE THREAD

**Issue by onplot** [switch2osm/switch2osm.github.io#128] opened 2020-06-16 07:42 UTC
Great article and the only one I've found that actually works for installing postgres/postgis....HOWEVER...as a complete newbie to Ubuntu things have gone wrong - even though I followed the instructions to the letter.

Following the instructions I got as far as doing the actual osm2pgsql with the downloaded file and got loads of errors - I had also got errors on the prior step carto project.mml > mapnik.xml I think it was

I think the problem is with the user I'm logged on as when I get to the Mapnik install (logged in as my root user) and I think it needs to be the render account.  My reasoning is that in the steps before "Installing osm2pgsql" we exited back out of the render account, then created a Unix user for the render account - nothing said about switching accounts.  When we get to "Compile the mod_tile source code" make command it says it should finish with 'Leaving directory /home/renderaccount/src/mod_tile'  but I'm logged in as root and there hasn't been a step to change user.

So from trying the om2pgsql I went back and tried to "git clone -b switch2osm git://github.com/SomeoneElseOSM/mod_tile.git" as the renderaccount but it said it was full so did the next steps and all went ok until "sudo make install" error: "renderaccount is not in the sudoers file. This incident will be reported"  So I figured try it without the sudo and I got loads of errors at the end:

make[2]: ***[Makefile:392 install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/home/renderaccount/src/mod_tile/iniparser3.0b'
make[1]: ***[Makefile:582 install-am] Error 2
make[1]: Leaving directory '/home/renderaccount/src/mod_tile/iniparser3.0b'  
make: ***[Makefile:1341: install-recursive] Error 1

So how do I get this resolved please and have I corrupted anything on the way?  I literally installed 20.04 server then I installed MATE GUI (only so I could copy and paste the code directly from the webpage so there would be no errors) and then started following your instructions

**Comment by SomeoneElseOSM** [comment] 2020-11-25 21:03
I think part of the problem is that I'm coming from an Ubuntu (and commercial Unix/Linux) background where you try and avoid doing anything as root, so I'd never think of even creating a root user on Ubuntu, never mind using it.

If you could provide a log of what you did and what went wrong that'd be useful, as it'll show where things are missing.

> I literally installed 20.04 server then I installed MATE GUI (only so I could copy and paste the code directly from the webpage so there would be no errors) 

Just for completeness - if you've got a server running without a gui you can ssh to it and copy and paste text into that ssh session.

**Comment by codydaig** [comment] 2021-02-14 17:56
I think the biggest issue that I can assume from this (having just followed this myself) Is that the guide has you create `renderaccount` separate from the account you log into the server with. But that account doesn't have sudo, however, it assumes you do when running several sudo commands that (until you get down into it) are supposed to be in `/home/renderaccount`. I ended up restarting on a fresh VM and doing everything from the non root account that I created with sudo privilege's. Following the instructions in the guide doesn't actually work because of the inconsistencies in which user you are supposed to be using. Does that make sense?

**Comment by SomeoneElseOSM** [comment] 2021-02-14 19:03
@codydaig I've added an extra paragraph to try and clarify things: https://github.com/switch2osm/switch2osm.github.io/pull/147/files .  That'll appear on the website shortly.  Is that better?

**Comment by codydaig** [comment] 2021-02-15 17:25
LGTM!

**Comment by SomeoneElseOSM** [comment] 2021-02-15 18:16
I'll close this since earlier updates to this and other pages tried to say "don't try this as root.  @onplot if there are any specific other things that you think should be added, please let us know.

**Closed by SomeoneElseOSM** 2021-02-15 18:16 UTC
